spring:
  redis:
    port: 6379
    host: 192.168.159.130

  rabbitmq:
    host: 192.168.0.154
    port: 5672
    virtual-host: /
    username: guest
    password: guest
    publisher-confirms: true #如果对异步消息需要回调必须设置为true
    listener:
      simple:
        concurrency: 1 #最小消费者
        max-concurrency: 1 #最大消费者


  datasource:
    url: jdbc:mysql://192.168.0.154:3306/vusd_server?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: test

    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 9700
mybatis-plus:
  # MyBatis Mapper所对应的XML文件位置
  mapper-locations: classpath*:/mapper/*Mapper.xml